service: myserverless-schedule

provider:
    name: aws
    runtime: nodejs12.x
    profile: default
    region: eu-west-1
    iamRoleStatements:
        - Effect: Allow
          Action:
              - ses:*
          Resource: '*'
functions:
    sendReminder:
        handler: lambdas/scheduleTasks/reminderEmail.handler
        events:
            - schedule: cron(40 13 * * ? *)
